### PR TITLE
Address compilation issues with recent MinGW-w64 related to ncurses, pthread, etc.

### PR DESCRIPTION
**Pull request by chappjc**
Address compilation issues with recent MinGW-w64 related to: ncurses, pthread, sleep, etc.
Allow including ATI/AMD OpenCL toolkits via environment variables as already allowed on non-win32.
See [original commit message](https://github.com/chappjc/cgminer/commit/91e820422572b9c2da9a24982bb6facebef11a7a) for details.

### CODE REVIEW

**Comment by chappjc** [comment]
Also tested on Arch Linux.

uname: 4.3.3-3-ARCH #1 SMP PREEMPT Wed Jan 20 08:12:23 CET 2016 x86_64 unknown GNU/Linux)
gcc version 5.3.0

<pre>------------------------------------------------------------------------
cgminer 3.7.2
------------------------------------------------------------------------
Configuration Options Summary:
  libcurl(GBT+getwork).: Enabled: -lcurl
  curses.TUI...........: FOUND: -lncurses
  OpenCL...............: FOUND. GPU mining support enabled
  scrypt...............: Disabled
  ADL..................: SDK found, GPU monitoring support enabled
  Avalon.ASICs.........: Disabled
  BFL.ASICs............: Disabled
  KnC.ASICs............: Disabled
  BitForce.FPGAs.......: Disabled
  BitFury.ASICs........: Disabled
  Hashfast.ASICs.......: Disabled
  BlackArrow.ASICs.....: Disabled
  Icarus.ASICs/FPGAs...: Disabled
  Klondike.ASICs.......: Disabled
  ModMiner.FPGAs.......: Disabled
Compilation............: make (or gmake)
  CPPFLAGS.............:
  CFLAGS...............: -g -O2
  LDFLAGS..............:  -lpthread
  LDADD................: -ldl -lcurl compat/jansson-2.5/src/.libs/libjansson.a -lpthread -L/home/jon/AMDAPPSDK/AMDAPPSDK-3.0/lib/x86_64 -lOpenCL    -lm  -lrt
Installation...........: make install (as root if needed, with 'su' or 'sudo')
  prefix...............: /usr/local
</pre>

**Comment by davecgh** [comment]
UPDATE:  Looks like you need the ncurses lib from the mingw64 repo instead of the msys one.

```
$  pacman -S mingw64/mingw-w64-x86_64-ncurses
```

I've been trying this PR under MSYS2, but it can't seem to find ncurses even though it's installed:

```
$ pacman -Qs curse
local/ncurses 6.0.20151121-1 (base)
    System V Release 4.0 curses emulation library
local/ncurses-devel 6.0.20151121-1 (development)
    NCURSES headers and libraries

$ ls -al /usr/lib/libncurses*
-rw-r--r-- 1 davec None 576K nov 23 00:44 /usr/lib/libncurses.a
-rw-r--r-- 1 davec None 444K nov 23 00:44 /usr/lib/libncurses.dll.a
-rw-r--r-- 1 davec None 143K nov 23 00:44 /usr/lib/libncurses++w.a
-rw-r--r-- 1 davec None 175K nov 23 00:44 /usr/lib/libncurses++w.dll.a
-rw-r--r-- 1 davec None 576K nov 23 00:44 /usr/lib/libncursesw.a
-rw-r--r-- 1 davec None 444K nov 23 00:44 /usr/lib/libncursesw.dll.a
```

```
$ export AMDAPPSDKROOT=/c/AMDAPPSDK/3.0
$ NOCONFIGURE=true ./autogen.sh
...
$ ./configure --enable-opencl
...
configure: WARNING: Could not find curses library - if you want a TUI, install libncurses-dev or pdcurses-dev
...
Configuration Options Summary:

  libcurl(GBT+getwork).: Enabled: -lcurl -lidn -liconv -lssh2 -lssl -lz -lcrypto -lz -lssl -lcrypto -lgdi32 -lssl -lz -lcrypto -lz
  curses.TUI...........: NOT FOUND. TUI support DISABLED
  OpenCL...............: NOT FOUND. GPU mining support DISABLED
```

EDIT: Update regarding OpenCL as I had a typo in the AMDAPPSDKROOT env variable.

**Comment by davecgh** [comment]
After getting the appropriate ncurses dep and futzing with the AMD APP SDK install a bit to get the deps in the expected place, I was able to get the 64-bit version to build under MSYS2.

```
Configuration Options Summary:

  libcurl(GBT+getwork).: Enabled: -L/mingw64/lib -lcurl -lidn -lrtmp -lssh2 -lssl -lcrypto -lssl -lcrypto -lgdi32 -lwldap32 -lz -lws2_32
  curses.TUI...........: FOUND: -lncurses
  OpenCL...............: FOUND. GPU mining support enabled
  scrypt...............: Disabled
  ADL..................: SDK found, GPU monitoring support enabled
```

So, looks good to me.

OK

**Comment by chappjc** [comment]
@davecgh Glad it works on your end.  Note that one quirk of MSYS2's mintty console that I haven't been able to work around for testing is that I can't actually start cgminer with curses enabled while in a MSYS2 shell, only a regular Windows command prompt.  It's probably an issue with either mintty or the ncurses runtime setup.  Either way, it's not a problem with the output binary -- I can't get any programs with pdcurses or ncurses to run in the MSYS2 shell, (including the official pdcurses samples!), but they all work great in cmd.exe.

For reference, I'm building with 3 configs:
- Windows 7 build machine with MSYS2's MinGW64 compiler packages.
- Arch Linux build machine with native target.
- Arch Linux build machine with MinGW64 (the one cross-compile setup).

**Comment by davecgh** [comment]
I noticed the same thing with MSYS2's mintty console.  It also noticed it doesn't work right with cmd.exe running under [ConEmu](https://conemu.github.io/) whereas the existing binary does.

That said, it does work fine everywhere in text mode (-T).

EDIT: Also, I should also point out that it does work properly under a normal cmd.exe window for me as well as you already noted.

**Comment by chappjc** [comment]
I might try pdcurses, but it's strange that the official demos (firework.exe, etc.) had the same issue.  That's why I concluded it must be a misconfigured shell or runtime library.

**Comment by jcvernaleo** [comment]
Looks good.  OK.

**Comment by chappjc** [comment]
@davecgh I had another look at the "Error opening terminal: dumb/xterm-256color/whatever" issue.  Apparently this has been a lingering issue for years.  [I found someone's workaround on BitCoin.StackExchange](http://bitcoin.stackexchange.com/a/14004/32753), which at least worked to fix it in ConEmu without having to disable curses.  Unfortunately, in mintty, it defaulted to text-only mode seemingly automatically regardless of what I set `TERM` to.

**Comment by davecgh** [comment]
@chappjc Interesting.  That workaround doesn't work for me under ConEmu (using cmd.exe under ConEmu that is).

**Pull request merged**
