### PR TITLE
Fixed high CPU usage and time-too-new bug.

### PR DESCRIPTION
**Pull request by jcvernaleo**

### CODE REVIEW

**Comment by jcvernaleo** [comment]
@jolan Guess what?  Another one for you to test build.

**Comment by raedah** [comment]
What is time-too-new bug?

**Comment by jolan** [comment]
"time-too-new" is an error seen on suprnova when submitting a share.

**Comment by jolan** [comment]
tACK

**Comment by chappjc** [comment]
Doesn't seem to fix CPU usage, as I mentioned in https://github.com/decred/cgminer/issues/20

It seems like something should set `work->MidstateValid=true;`.  When `precalc_hash_blake256` finishes the first time for current work?  Dunno... haven't studied this code.

**Pull request merged**
