### PR TITLE
Added some required build flags.

### PR DESCRIPTION
**Pull request by jcvernaleo**

### CODE REVIEW

**Comment by jcvernaleo** [comment]
@jolan could you also sanity test this one?

**Comment by chappjc** [comment]
Why gnu11 and not c++11?  If the GNU extensions aren't used, why limit the compiler?  Will it break icc for example?

I think msse2 is ignored for x86_64.  <s>Haven't checked for a warning though.</s>  Compiler doesn't warn, so I guess nevermind.  :)

**Comment by jolan** [comment]
tACK.

Yes -msse2 is actually the default on x86_64, this is for forcing SSE2 on x86.

We can take out -std=gnu11 after we have our build scripts completed and see if they still work.

Doesn't seem like it may actually be needed. The gcc manual says "The default, if no C language dialect options are given, is -std=gnu11."

**Comment by jcvernaleo** [comment]
Since we are really only targeting amd64, is there any value to this change?

**Comment by jolan** [comment]
I don't think so.

**Comment by jcvernaleo** [comment]
So based on the discussion above I'm closing this one rather than merging it.  But for reference, it was from commit ffd746f29baac19eca0bc1c221f054ce0fecee39 in wolf's tree.

**Pull request closed without merging**
