### PR TITLE
.gitignore the rest of the generated files.

### PR DESCRIPTION
**Pull request by jcvernaleo**

### CODE REVIEW

**Comment by tpruvot** [comment]
you should just put m4/ folder or *.m4 and *.lo

**Comment by jcvernaleo** [comment]
Good point about the *.lo files.  I'll update for that.
As for m4, I thought I saw some files in there that were check in to git so I wasn't sure what there status was.  I'll look at it again though to be sure.

**Comment by tpruvot** [comment]
if there was a .m4 added in the git, it will still be tracked... until a git rm... .gitignore files are just made to prevent "untracked files" entries in "git status". "git add -f ignored.file" still works if really required..

**Comment by jcvernaleo** [comment]
How's this look?  A bit more compact I think.
@jolan any opinion?

**Comment by jolan** [comment]
Fine by me.

**Pull request merged**
