### PR TITLE
Linux build script fixes

### PR DESCRIPTION
**Pull request by chappjc**
Do not assume name of repo directory is "cgminer".  Handle unzip and copy when files exist w/o write permissions.

### CODE REVIEW

**Comment by chappjc** [comment]
OK, I didn't squash/rebase this.  What's the right way to do this?  I don't get why those extra commits are here.

**Comment by jcvernaleo** [comment]
Change looks good to me.  @chappjc could you make the commit a little more descriptive?  What you said in the PR is perfect, but the commit itself doesn't say much.  You can always do git commit --amend and then git push -f you branch so it just updates the PR then I'll merge it in.  Thanks!

**Comment by chappjc** [comment]
I need to stop doing commit -m, and use the editor.  :)

**Comment by jcvernaleo** [comment]
Thanks!  Getting it in now.
OK

**Pull request merged**
