### PR TITLE
blake kernel optimisation for nvidia cards

### PR DESCRIPTION
**Pull request by tpruvot**
part of my tasks in the RFP-5

Signed-off-by: Tanguy Pruvot tanguy.pruvot@gmail.com

### CODE REVIEW

**Comment by jcvernaleo** [comment]
@tpruvot really sorry for taking so long before getting to this PR.
So I can't test or benchmark this myself (no nvidia hardware) but I did go through the code pretty well.  Looks good.  One question (which I'll put as a separate comment so I can attach it to the right line).

**Comment by jcvernaleo** [comment]
Actually, it appears github will not let me do the line by line comment (diff to large maybe?).
Is there a reason that in the code after    /\* 14 rounds */ you made each round a single line rather than the original code which had each statement on a line?  I found the single line with multiple statements much harder to read.

**Comment by tpruvot** [comment]
no real reason, its how it was done in other blake kernels

**Comment by jolan** [comment]
tACK

Mined on testnet with this. 2 blocks on fast AMD hardware before quitting, 2 on Intel, and a couple dozen on Nvidia.

**Comment by cjepson** [comment]
utACK

OK for merge

**Pull request merged**
